# Generated by Django 2.1.5 on 2021-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0002_auto_20210915_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
